language: go

go:
  - 1.9.x
  - 1.10.x
  - master

git:
  depth: 1

intall: true

notifications:
  email: false

before_script:
  - sudo wget https://github.com/51Degrees/Device-Detection/blob/master/data/51Degrees-LiteV3.2.dat

script:
  - go test -v -race ./...